#!/bin/sh 
#This job should be redirected to idqueue
#PBS -N OMPHelloWorld_24threads
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:02:00
#PBS -l place=scatter
#PBS -l accelerator_type="None"
#PBS -S /bin/sh@sdb -V 
export OMP_NUM_THREADS=24
. /opt/modules/default/init/sh
cd /home/proj/16/secpraba/2019MayOPENMP/OMPSchedules
aprun -j 1 -n 1 -N 1 -d $OMP_NUM_THREADS ./Ex2Schedules.out 

